# image will be published to ghcr.io/<user>/<name>
name: uMeow
# description will be included in the image's metadata
description: Cute OS for cute kitty

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/kinoite-main
image-version: 40 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - from-file: recipes/modules/files.yml
  - from-file: recipes/modules/fonts.yml
  - from-file: recipes/modules/packages.yml
  - from-file: recipes/modules/flatpaks.yml
  - type: yafti
  - type: signing # this sets up the proper policy & signing files for signed images to work fully

