title: Welcome to uMeow :3

properties:
  mode: "run-once"
  path: "~/.config/yafti/last-run"

screens:
  first-screen:
    source: yafti.screen.title
    values:
      title: Welcome to uMeow :3
      description: |
        Lets make the purrfect kittyputer UwU

  check-no-fedora-flatpak:
    source: yafti.screen.consent
    values:
      title: Wemoving fedora flatpaks?
      condition:
        run: flatpak remotes --columns=name | grep fedora
      description: |
        Fedora flatpak wemote was found :c Do you want to weplace it with flathub? This is wequiwed fow yafti to nyanstall flatpaks, and this will also wemove all installed flatpaks.
      actions:
        - run: flatpak remove --noninteractive --all && flatpak remote-delete --system fedora && flatpak remote-delete --user fedora && flatpak remote-add --if-not-exists --system flathub https://dl.flathub.org/repo/flathub.flatpakrepo

  check-system-flathub:
    source: yafti.screen.consent
    values:
      title: Nyo flathub wepo OwO
      condition:
        run: flatpak remotes --system --columns=name | grep flathub | wc -l | grep '^0$'
      description: |
        Flathub wemote is nyot installed :c Do you want to nyanstall it? :3 This is wequiwed fow yafti to nyanstall flatpaks
      actions:
        - run: flatpak remote-add --if-not-exists --system flathub https://dl.flathub.org/repo/flathub.flatpakrepo

  applications:
    source: yafti.screen.package
    values:
      title: All the appitty apps!
      show_terminal: true
      package_manager: yafti.plugin.flatpak
      package_manager_defaults:
        user: false
        system: true
      groups:
        KDE Gear:
          description: KDE stuffs!
          default: true
          packages:
            - Kcalc: org.kde.kcalc
            - Gwenview: org.kde.gwenview
            - Okular: org.kde.okular
            - Elisa: org.kde.elisa
            - Kolourpaint: org.kde.kolourpaint
        Cweative:
          description: Stuff to make kewl media with
          default: false
          packages:
            - Krita: org.kde.krita
            - Video Editing (Kdenlive): org.kde.kdenlive
            - Codecs do the shuffle (Handbrake): fr.handbrake.ghb
            - The best 3D anyamation/VFX softwawe evew (Blender): org.blender.Blender
            - Make 3D pweview images (Exhibit): io.github.nokse22.Exhibit
        Intewnet:
          description: Wowld fluffy net for meow
          default: true
          packages:
            - Firefox: org.mozilla.firefox
            - Ungoogle Chromium: io.github.ungoogled_software.ungoogled_chromium
            - Discord but better (Veskto (Vesktop)p): dev.vencord.vesktop
            - Discord but worse (matrix): org.kde.neochat
        Audio wouting:
          description: Make meows sound good :3
          default: true
          packages:
            - qpwgraph: org.rncbc.qpwgraph
            - EasyEffects: com.github.wwmm.easyeffects
        Development:
          description: Lots of fun for smort kitties
          default: true
          packages:
            - HTTPie: io.httpie.Httpie
            - Podman Desktop: io.podman_desktop.PodmanDesktop
            - Gnome Workbench: re.sonny.Workbench
        Media and Office:
          description: Bowing but also watch stuffs!
          default: true
          packages:
            - Obfuscate all the thingies: com.belmoussaoui.Obfuscate
            - LibreOffice: org.libreoffice.LibreOffice
            - VLC: org.videolan.VLC
            - Plots: com.github.alexhuntley.Plots
        Other:
          description: Queer meows
          default: false
          packages:
            - Calligraphy (text to ascii art): dev.geopjr.Calligraphy
            - Type Racing: dev.bragefuglseth.Keypunch
            - Railway (train info): de.schmidhuberj.DieBahn
            - Cavalier (funny music visualisation): org.nickvision.cavalier

  steam:
    source: yafti.screen.consent
    values:
      title: Nyanstall Steam?
      description: Nyanstall Steam? Would be layewed because flatpak version has no access to drm leasing for VR
      actions:
        - run: rpm-ostree install steam steam-devices -yq

  config:
    source: yafti.screen.consent
    values:
      title: meowfig nyanstallation
      description: Do meow want to nyanstall meowfig configs?
      actions:
        - run: /usr/libexec/get_melody_config.sh
